[package]
name = "shared"
version = "0.1.0"
edition = "2024"


[lib]
name = "shared"

[dependencies]
rand = { workspace = true }
anyhow = { workspace = true }

dotenv = { workspace = true }
envy = { workspace = true }
serde = { workspace = true }

